
INSERT INTO `KL_KALKULACIJAS_GRUPAS` (`KKLG_ID`, `KKLG_KODS`, `KKLG_NOSAUKUMS`, `KKLG_IR_AKTIVS`)
VALUES ('17', '21', 'Zemes darbi, virsmas, trases', '1');
INSERT INTO `KL_KALKULACIJAS_GRUPAS` (`KKLG_ID`, `KKLG_KODS`, `KKLG_NOSAUKUMS`, `KKLG_IR_AKTIVS`)
VALUES ('18', '22', 'ZS kabeïu lîniju darbi', '1');
INSERT INTO `KL_KALKULACIJAS_GRUPAS` (`KKLG_ID`, `KKLG_KODS`, `KKLG_NOSAUKUMS`, `KKLG_IR_AKTIVS`)
VALUES ('19', '23', 'VS kabeïu lîniju darbi', '1');
INSERT INTO `KL_KALKULACIJAS_GRUPAS` (`KKLG_ID`, `KKLG_KODS`, `KKLG_NOSAUKUMS`, `KKLG_IR_AKTIVS`)
VALUES ('20', '24', 'ZS gaisvadu lîniju darbi', '1');
INSERT INTO `KL_KALKULACIJAS_GRUPAS` (`KKLG_ID`, `KKLG_KODS`, `KKLG_NOSAUKUMS`, `KKLG_IR_AKTIVS`)
VALUES ('21', '25', 'VS gaisvadu lîniju darbi', '1');
INSERT INTO `KL_KALKULACIJAS_GRUPAS` (`KKLG_ID`, `KKLG_KODS`, `KKLG_NOSAUKUMS`, `KKLG_IR_AKTIVS`)
VALUES ('22', '26', 'ZS sadalòu montâþas darbi', '1');
INSERT INTO `KL_KALKULACIJAS_GRUPAS` (`KKLG_ID`, `KKLG_KODS`, `KKLG_NOSAUKUMS`, `KKLG_IR_AKTIVS`)
VALUES ('23', '27', 'TP, KP un SP montâþas darbi', '1');
INSERT INTO `KL_KALKULACIJAS_GRUPAS` (`KKLG_ID`, `KKLG_KODS`, `KKLG_NOSAUKUMS`, `KKLG_IR_AKTIVS`)
VALUES ('24', '28', 'Zemçjumu montâþas darbi', '1');
INSERT INTO `KL_KALKULACIJAS_GRUPAS` (`KKLG_ID`, `KKLG_KODS`, `KKLG_NOSAUKUMS`, `KKLG_IR_AKTIVS`)
VALUES ('25', '29', 'Citi darbi', '1');
INSERT INTO `KL_KALKULACIJAS_GRUPAS` (`KKLG_ID`, `KKLG_KODS`, `KKLG_NOSAUKUMS`, `KKLG_IR_AKTIVS`)
VALUES ('26', '31', 'RAA un TM darbi', '1');

INSERT INTO `KL_REF_KODI` (
`KRFK_ID` ,
`KRFK_NOSAUKUMS` ,
`KRFK_VERTIBA` ,
`KRFK_NOZIME`
)
VALUES ('47', 'SECTION', 'Daugavpils', 'Daugavpils' ),
('48', 'SECTION', 'Preili', 'Preiïi')  ,
('49', 'SECTION', 'Ludza', 'Ludza') ,
('50', 'SECTION', 'Kraslava', 'Krâslava') ,
('51', 'SECTION', 'Rezekne', 'Rçzekne')
;


/*ALTER TABLE `KL_KALKULACIJA` CHANGE `KKAL_MERVIENIBA` `KKAL_MERVIENIBA` VARCHAR( 25 ) CHARACTER SET utf8 COLLATE utf8_latvian_ci NOT NULL ;

SELECT * FROM `kl_kalkulacija` WHERE  KKAL_GRUPAS_KODS  IN
(21,22,23,24,25,26,27,28,29,31);
DELETE FROM `kl_kalkulacija` WHERE  KKAL_GRUPAS_KODS  IN
(21,22,23,24,25,26,27,28,29,31);
*/
emp_mkox / mpower
4c165f53a910a6a605c470bb2bd1debe

getKrfkTextByName