CREATE TABLE IF NOT EXISTS `KL_KALKULACIJA_TRASE` (
  `KKAL_ID` int(11) NOT NULL auto_increment,
  `KKAL_GRUPAS_KODS` char(5) collate utf8_latvian_ci NOT NULL,
  `KKAL_SHIFRS` char(5) collate utf8_latvian_ci NOT NULL,
  `KKAL_NOSAUKUMS` varchar(150) collate utf8_latvian_ci NOT NULL,
  `KKAL_APRAKSTS` text collate utf8_latvian_ci,
  `KKAL_MERVIENIBA` varchar(15) collate utf8_latvian_ci NOT NULL,
  `KKAL_IR_AKTIVS` tinyint(1) NOT NULL default '1',
  `KKAL_FIZ_RADIJUMS` varchar(4) collate utf8_latvian_ci default NULL,
  `KKAL_KEDI_SECTION` varchar(250) collate utf8_latvian_ci default NULL,
  `KKAL_KWOI_KODS` varchar(13) collate utf8_latvian_ci default NULL,
  `KKAL_PLAN_PRICE` float(7,2) default NULL,
  `KKAL_NOT_PLAN_PRICE` float(7,2) default NULL,

  `KKAL_IS_ELEMENT` tinyint(1) default '0',
  `KKAL_KOEFICENT` float(5,2) default '1.00',
  PRIMARY KEY  (`KKAL_ID`),
  KEY `KKAL_GRUPAS_KODS` (`KKAL_GRUPAS_KODS`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_latvian_ci AUTO_INCREMENT=1 ;

INSERT INTO `KL_REF_KODI` (
`KRFK_ID` ,
`KRFK_NOSAUKUMS` ,
`KRFK_VERTIBA` ,
`KRFK_NOZIME`
)
VALUES (
NULL , 'IMPORTS', 'KALKULATION_TR', 'Traðu tîrîðanas kalkulâcijas'
);

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES
('TRASES', 'Trases'),
('TRASE_KALCULATION', 'Trases kalkulâcija');

INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES (
'KKAL_SHIFRS', 'Ðifrs', 'KL_KALKULACIJA_TRASE', '1'
), (
 'GROUP', 'Grupa', 'KL_KALKULACIJA_TRASE', '0'
);

INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES
('KKAL_NOSAUKUMS', 'Nosaukums', 'KL_KALKULACIJA_TRASE', '0' ),
('WORKER', 'Darbauzòçmçjs', 'KL_KALKULACIJA_TRASE', '0'),
('KKAL_KEDI_SECTION', 'ED iecirknis', 'KL_KALKULACIJA_TRASE', '0'),
('KKAL_IR_AKTIVS', 'Ir aktîvs (1/0)', 'KL_KALKULACIJA_TRASE', '0'),
('KKAL_FIZ_RADIJUMS', 'Fiz. râdîtâjs', 'KL_KALKULACIJA_TRASE', '0');

ALTER TABLE `LIETOTAJI` ADD `RLTT_IR_TRASE` INT( 1 ) NOT NULL DEFAULT '0' AFTER `RLTT_KEDI_SECTION` ;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)  VALUES ('TRASE_USER', 'Traðu tîrîtâjs');

INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES (
'RLTT_IR_TRASE', 'Traðu tîrîtâjs (1/0)', 'KL_LIETOTAJI_DU', '0'
);
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)  VALUES ('MMS_KOKNESE', 'Koksne');
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)  VALUES ('MMS_PLAN_PAYMENT', 'Plânotâs izmaksas');

ALTER TABLE `KL_REF_KOLONNAS` CHANGE `KLKL_TITLE` `KLKL_TITLE` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_latvian_ci NOT NULL;

UPDATE `KL_REF_KOLONNAS` SET `KLKL_TITLE` = 'Materiâla izmaksas / Plânotâs izmaksas' WHERE `KLKL_COLUMN` = 'KMSD_MATR_IZMAKSAS';


INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES ('KMSD_CILVEKSTUNDAS', 'Cilvçkstunda / Koksne ', 'KL_MMS_DARBI', '0' ),
('KMSD_TRASE', 'DU trases (1/0)', 'KL_MMS_DARBI', '0' );



ALTER TABLE `AKTI` ADD `RAKT_TRASE` TINYINT( 1 ) NOT NULL DEFAULT '0' AFTER `RAKT_KWRC_ID` ;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES
('ACT_CREATER', 'Aktu izveidoja'),
('OUNER_CHIF', 'vadîtâjs'),
('OUNER_MASTER', 'meistars'),
('IN_REPORT_SECTION', 'nodaïas');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES
('TRASE_ACT_HEADER1', 'PAKALPOJUMA PIEÒEMÐANAS - NODOÐANAS AKTS'),
('NUMBER_SIMBOL', 'Nr'),
('TRASE_ACT_HEADER2', 'Traðu attîrîðana no apauguma'),
('IN_YEAR', 'gada'),
('MASTER_SECTION', 'meistara iecirknis');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES
('REPORT_WORK_DONE', 'Darbu izpildîtâjs'),
('REGISTRATION_SIMBOL', 'reì'),
('WORK_DONE_AGREEMENT_NO', 'Darbu izpilde saskaòâ ar Vienoðanos Nr.'),
('IN_PERIOD', 'par'),
('TRASE_ACT_HEADER3', 'mçnesi izpildîto darbu pieòemðanu');

-- 31.03.2013
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES
('ACT_NUMBER_TEMPLATE', 'Akta numura ðabloni'),
('TEXT_TEMPLATE', 'Teksta ðablons'),
('LINK_TEMPLATE', 'Linka ðablons');
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES
('ERROR_ALPHA_VALUE', 'Lauks var saturçt tikai sekojoðus simbolus `A-Z`.'),
('ERROR_URL_VALUE', 'Lauks var saturçt hiperlinku.');

ALTER TABLE `SYSTEM_INFO` ADD `SNFO_TEXT_TMPL` VARCHAR( 8 ) NULL AFTER `SNFO_WARNING` ,
ADD `SNFO_LINK_TMPL` VARCHAR( 200 ) NULL AFTER `SNFO_TEXT_TMPL`;

ALTER TABLE `AKTI` CHANGE `RAKT_FULL_NUMBER` `RAKT_FULL_NUMBER` VARCHAR( 40 ) NULL DEFAULT '';
ALTER TABLE `AKTI` ADD `RAKT_NUM_POSTFIX` VARCHAR( 20 ) NULL AFTER `RAKT_TRASE`;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES  ('ACT_NUM_POSTFIX', 'Akta numura postfix');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES  ('ERROR_ACT_NUM_POSTFIX', 'Akta numura postfix ir sastadîts nepareizi!');

ALTER TABLE `KL_AKTA_VEIDS` ADD `KAKV_TRASE` TINYINT( 1 ) NOT NULL DEFAULT 0;

INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES ( 'KAKV_TRASE', ' DU trases (1/0)', 'KL_AKTA_VEIDS', '0' );

ALTER TABLE `FAILI` CHANGE `RFLS_NOSAUKUMS` `RFLS_NOSAUKUMS` VARCHAR( 100 ) CHARACTER SET utf8 COLLATE utf8_latvian_ci NOT NULL  ;

UPDATE  `KL_REF_KOLONNAS` SET `KLKL_TITLE` =  'Cilvçkstunda / Koksne' WHERE  `KLKL_COLUMN` = 'KMSD_CILVEKSTUNDAS';
UPDATE  `FMK_MESSAGES` SET `TEXT` =  'Koksne' WHERE  `CODE` = 'MMS_KOKNESE';

-- 21.04
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES  ('REPORT_MMS_CALC', 'MMS darba izpilde');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES  ('PLAN_CODE', 'Plâna kods'),
('PLAN_AMOUNT', 'Plâna apjoms'),
('DONE_AMOUNT', 'Izpildes apjoms'),
('PAYMENT_AMOUNT', 'Izmalsas');

-- 27.04
ALTER TABLE `KL_WORK_OWNERS` ADD `KWOI_TRASE_VV_NUMBER` VARCHAR( 20 ) CHARACTER SET utf8 COLLATE utf8_latvian_ci NULL AFTER `KWOI_VV_NUMBER`;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES  ('KWOI_TRASE_VV_NUMBER', 'Traðu tîrîðanas Vispârîgâs vienoðanâs nr.');

INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES ( 'KWOI_TRASE_VV_NUMBER', 'Traðu tîrîðanas Vispârîgâs vienoðanâs nr.', 'KL_DARBA_UZNEMEJI', '0'    );

UPDATE`FMK_MESSAGES` SET `TEXT` = 'KvikSteps kods' WHERE `CODE` = 'ACT_NUM_POSTFIX';
UPDATE`FMK_MESSAGES` SET `TEXT` = 'Akts par izpildîto darbu pieòemðanu' WHERE `CODE` = 'TRASE_ACT_HEADER3';

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES('JANUARYT', 'janvârî'),
('FEBRUARYT', 'februârî'),
('MARCHT', 'martâ'),
('APRILT', 'aprîlî'),
('MAYT', 'maijâ'),
('JUNET', 'jûnijâ'),
('JULYT', 'jûlijâ'),
('AUGUSTT', 'augustâ'),
('SEPTEMBERT', 'septembrî'),
('OCTOBERT', 'oktobrî'),
('NOVEMBERT', 'novembrî'),
('DECEMBERT', 'decembrî');




UPDATE`FMK_MESSAGES` SET `TEXT` = 'KvikStepa kods ir sastâdîts nepareizi. Koda ievades formâts `AAA-xxxxx`, kur A-burts, x-skaitlis' WHERE `CODE` = 'ERROR_ACT_NUM_POSTFIX';

UPDATE`FMK_MESSAGES` SET `TEXT` = 'Plânotais apjoms' WHERE `CODE` = 'PLAN_AMOUNT';
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES  ('PLAN_PRICES', 'Plânotâs izmaksas, LVL');

-- 22.05.2013
INSERT INTO  `KL_WRITEOFF_CODE` (
`KWRC_ID` ,
`KWRC_KAKV_ID` ,
`KWRC_KOBJ_ID` ,
`KWRC_TITLE`
)
VALUES (
NULL ,  '1',  '99',  '71876 - Sadales EPL traðu tîrîðana'
);

INSERT INTO  `FMK_MESSAGES` (
`id` ,
`code` ,
`text`
)
VALUES (
NULL ,  'TRASE_WORK',  'Traðu tîrîðana'
);


ALTER TABLE `KL_OBJEKTI` ADD `KOBJ_TRASE` TINYINT( 1 ) NOT NULL DEFAULT 0;

INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES ( 'KOBJ_TRASE', ' DU trases (1/0)', 'KL_OBJEKTI', '0' );

ALTER TABLE `KL_SPRIEGUMS` ADD `KSRG_TRASE` TINYINT( 1 ) NOT NULL DEFAULT 0;

INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES ( 'KSRG_TRASE', ' DU trases (1/0)', 'KL_SPRIEGUMS', '0' );

-- 23.05.2013
INSERT INTO  `KL_REF_KODI` (
`KRFK_ID` ,
`KRFK_NOSAUKUMS` ,
`KRFK_VERTIBA` ,
`KRFK_NOZIME`
)
VALUES (
NULL ,  'POSITION',  'GROUP_CHIF',  'Nodaïas vadîtâjs'
), (
NULL ,  'POSITION',  'DEPARTMENT_CHIF',  'Daïas vadîtâjs'
);
INSERT INTO  `KL_REF_KODI` (
`KRFK_ID` ,
`KRFK_NOSAUKUMS` ,
`KRFK_VERTIBA` ,
`KRFK_NOZIME`
)
VALUES  (
NULL ,  'POSITION',  'MASTER',  'Meistars'
);

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES  ('HARMONIZED', 'Saskaòotâji'),
('OPERATING_PART', 'Ekspluatâcijas daïa');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES ('POSITION', 'Amats');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES ('ERROR_EXISTS_HARMONIZED_NAME', 'Saskaòotâjs ar ðâdu vârdu un uzvârdu jau ir definçts.');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES ('HARMONIZED_INFO', 'Infirmâcija par saskaòotâju');

CREATE TABLE IF NOT EXISTS `KL_SASKANOTAJI` (
  `SLTT_ID` int(11) NOT NULL auto_increment,
  `SLTT_VARDS` varchar(30) collate utf8_latvian_ci NOT NULL default '',
  `SLTT_UZVARDS` varchar(30) collate utf8_latvian_ci NOT NULL default '',
  `SLTT_IR_AKTIVS` tinyint(1) NOT NULL default '1',
  `SLTT_KEDI_ID` int(11) default NULL,
  `SLTT_POSITION` varchar(100) collate utf8_latvian_ci NOT NULL,
  `SLTT_REGIONS` char(3) collate utf8_latvian_ci NOT NULL,
  `SLTT_KEDI_SECTION` varchar(250) collate utf8_latvian_ci NOT NULL,
  PRIMARY KEY  (`SLTT_ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_latvian_ci AUTO_INCREMENT=1 ;

INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES ( 'SLTT_VARDS', 'Vârds', 'KL_SASKANOTAJI', '0' ),
( 'SLTT_UZVARDS', 'Uzvârds', 'KL_SASKANOTAJI', '0' ),
( 'POSITION', 'Amats', 'KL_SASKANOTAJI', '1' ),
( 'SLTT_REGIONS', 'Reìions', 'KL_SASKANOTAJI', '0' ),
( 'AREA', 'ED iecirknis', 'KL_SASKANOTAJI', '0' ),
( 'SLTT_KEDI_SECTION', 'ED nodaïa', 'KL_SASKANOTAJI', '0' ),
( 'SLTT_IR_AKTIVS', 'Ir aktîvs (1/0)', 'KL_SASKANOTAJI', '0' );

INSERT INTO  `KL_REF_KODI` (
`KRFK_ID` ,
`KRFK_NOSAUKUMS` ,
`KRFK_VERTIBA` ,
`KRFK_NOZIME`
)
VALUES (
NULL ,  'POSITION',  'EKSPOATATION_ENGINEER',  'Elektroietaiðu ekspluatâcijas inþenieris'
), (
NULL ,  'POSITION',  'ENGINEER',  'Elektroinþenieris'
);

-- 24.05.2013
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES  ('TRASE_ACT_HEADER4', 'PAKALPOJUMA PIEÒEMÐANAS - NODOÐANAS AKTA SAGATAVI'),
('IS_NOT_ENDORSED', 'NAV elektroniski vizçts');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES  ('SIGN_HEADER', 'Darbus pieòçma un aktu elektroniski vizçja'),
('SIGN_MASTER', 'Nodaïas meistars'),
('SIGN_CHIF', 'Nodaïas vadîtâjs'),
('SIGN_ENGENEER', 'Reìiona atbildîgais inþenieris');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES ('IN_REGION', 'reìiona'),
('OUNER_ENGENEER', 'inþenieris'),
('LAIKS', 'plkst.'),
('OUNER_OPERATING_PART', 'Ekspluatâcijas daïa vadîtâjs');

INSERT INTO  `KL_REF_KODI` (
`KRFK_ID` ,
`KRFK_NOSAUKUMS` ,
`KRFK_VERTIBA` ,
`KRFK_NOZIME`
)
VALUES (NULL ,  'REGIONNAME',  'AR',  'Austrumu' ),
(NULL ,  'REGIONNAME',  'CR',  'Centrâlais' ) ,
(NULL ,  'REGIONNAME',  'DR',  'Dienvidu' ),
(NULL ,  'REGIONNAME',  'RR',  'Rietumu' ) ,
(NULL ,  'REGIONNAME',  'ZAR',  'Ziemeïaustrumu' ) ,
(NULL ,  'REGIONNAME',  'ZR',  'Ziemeïu' );





INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(1, 'Juris', 'Sticers', 1, 116, 'MASTER', 'ZAR', 'Aizkraukle');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(2, 'Armands', 'Kasparâns', 1, 117, 'MASTER', 'ZAR', 'Aizkraukle');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(3, 'Andris', 'Lakstîgala', 1, 118, 'MASTER', 'ZAR', 'Aizkraukle');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(4, 'Aigars', 'Zupa', 1, NULL, 'GROUP_CHIF', 'ZAR', 'Aizkraukle');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(5, 'Alfrçds', 'Bite', 1, 79, 'MASTER', 'RR', 'Aizpute');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(6, 'Armands', 'Dobelis', 1, 80, 'MASTER', 'RR', 'Aizpute');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(7, 'Âris', 'Troika', 1, 81, 'MASTER', 'RR', 'Aizpute');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(8, 'Zigmârs', 'Liparts', 1, NULL, 'GROUP_CHIF', 'RR', 'Aizpute');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(9, 'Mareks', 'Bçrtiòð', 1, 95, 'MASTER', 'ZAR', 'Alûksne');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(10, 'Austris', 'Trupovnieks', 1, 96, 'MASTER', 'ZAR', 'Alûksne');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(11, 'Kristaps', 'Paegle', 1, 97, 'MASTER', 'ZAR', 'Alûksne');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(12, 'Jânis', 'Hercogs', 1, NULL, 'GROUP_CHIF', 'ZAR', 'Alûksne');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(13, 'Edgars', 'Soldâns', 1, NULL, 'DEPARTMENT_CHIF', 'AR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(14, 'Genadijs', 'Miès', 1, 102, 'MASTER', 'ZAR', 'Balvi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(15, 'Juris', 'Gergenreders', 1, 103, 'MASTER', 'ZAR', 'Balvi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(16, 'Aldis', 'Dortâns', 1, 104, 'MASTER', 'ZAR', 'Balvi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(17, 'Andis', 'Loèmelis', 1, NULL, 'GROUP_CHIF', 'ZAR', 'Balvi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(18, 'Kaspars', 'Kalniòð', 1, 50, 'MASTER', 'DR', 'Bauska');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(19, 'Aleksandrs', 'Kalderauskis', 1, 51, 'MASTER', 'DR', 'Bauska');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(20, 'Ivars', 'Anduþs', 1, 52, 'MASTER', 'DR', 'Bauska');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(21, 'Raimonds', 'Freimanis', 1, 53, 'MASTER', 'DR', 'Bauska');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(22, 'Gundars', 'Krûmiòð', 1, NULL, 'GROUP_CHIF', 'DR', 'Bauska');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(23, 'Kârlis', 'Sproìis', 1, NULL, 'DEPARTMENT_CHIF', 'CR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(24, 'Agris', 'Jansons', 1, 125, 'MASTER', 'ZR', 'Cçsis');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(25, 'Mâris', 'Pûpe', 1, 126, 'MASTER', 'ZR', 'Cçsis');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(26, 'Andrejs', 'Vîksna', 1, 127, 'MASTER', 'ZR', 'Cçsis');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(27, 'Uìis', 'Asaris', 1, 142, 'MASTER', 'ZR', 'Cçsis');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(28, 'Edvîns', 'Zîtars', 1, 143, 'MASTER', 'ZR', 'Cçsis');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(29, 'Guntis', 'Loðins', 1, NULL, 'GROUP_CHIF', 'ZR', 'Cçsis');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(30, 'Vadims', 'Masâns', 1, 1, 'MASTER', 'AR', 'Daugavpils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(31, 'Vasilijs', 'Cjuperjaks', 1, 2, 'MASTER', 'AR', 'Daugavpils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(32, 'Çriks', 'Purvinskis', 1, 3, 'MASTER', 'AR', 'Daugavpils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(33, 'Anatolijs', 'Kuòko', 1, 4, 'MASTER', 'AR', 'Daugavpils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(34, 'Viktors', 'Smiïìins', 1, 5, 'MASTER', 'AR', 'Daugavpils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(35, 'Jânis', 'Guïâns', 1, 6, 'MASTER', 'AR', 'Daugavpils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(36, 'Dmitrijs', 'Rosolajs', 1, NULL, 'GROUP_CHIF', 'AR', 'Daugavpils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(37, 'Mâris', 'Bçrziòð', 1, NULL, 'DEPARTMENT_CHIF', 'DR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(38, 'Ìirts', 'Goþa', 1, 55, 'MASTER', 'DR', 'Dobele');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(39, 'Igors', 'Èuhnovs', 1, 56, 'MASTER', 'DR', 'Dobele');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(40, 'Mâra', 'Tarvîda', 1, 57, 'MASTER', 'DR', 'Dobele');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(41, 'Aivars', 'Dûms', 1, NULL, 'GROUP_CHIF', 'DR', 'Dobele');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(42, 'Ivars', 'Suseklis', 1, 99, 'MASTER', 'ZAR', 'Gulbene');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(43, 'Andris', 'Cîrulis', 1, 100, 'MASTER', 'ZAR', 'Gulbene');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(44, 'Mâris', 'Elksnis', 1, NULL, 'GROUP_CHIF', 'ZAR', 'Gulbene');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(45, 'Dmitrijs', 'Cimburovs', 1, 59, 'MASTER', 'DR', 'Jelgava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(46, 'Valçrijs', 'Denjuðèenkovs', 1, 60, 'MASTER', 'DR', 'Jelgava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(47, 'Igors', 'Ulmanis', 1, 61, 'MASTER', 'DR', 'Jelgava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(48, 'Ainârs', 'Kleíeris', 1, 62, 'MASTER', 'DR', 'Jelgava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(49, 'Aigars', 'Grînofs', 1, NULL, 'GROUP_CHIF', 'DR', 'Jelgava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(50, 'Nauris', 'Niedre', 1, 111, 'MASTER', 'ZAR', 'Jçkabpils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(51, 'Andis', 'Rûtiòð', 1, 112, 'MASTER', 'ZAR', 'Jçkabpils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(52, 'Harijs', 'Vilnis', 1, 113, 'MASTER', 'ZAR', 'Jçkabpils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(53, 'Vilis', 'Kalniòð', 1, 114, 'MASTER', 'ZAR', 'Jçkabpils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(54, 'Andris', 'Dilbeks', 1, NULL, 'GROUP_CHIF', 'ZAR', 'Jçkabpils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(55, 'Mâris', 'Zelès', 1, 28, 'MASTER', 'CR', 'Jugla');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(56, 'Viktors', 'Vindelis', 1, 29, 'MASTER', 'CR', 'Jugla');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(57, 'Gatis', 'Melnis', 1, 30, 'MASTER', 'CR', 'Jugla');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(58, 'Mârtiòð', 'Vanags', 1, 145, 'MASTER', 'CR', 'Jugla');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(59, 'Uldis', 'Vîtols', 1, 146, 'MASTER', 'CR', 'Jugla');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(60, 'Jânis', 'Kurkulîtis', 1, NULL, 'GROUP_CHIF', 'CR', 'Jugla');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(61, 'Juris', 'Hohs', 1, 47, 'MASTER', 'CR', 'Jûrmala');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(62, 'Normunds', 'Vçveris', 1, 48, 'MASTER', 'CR', 'Jûrmala');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(63, 'Dainis', 'Çvele', 1, NULL, 'GROUP_CHIF', 'CR', 'Jûrmala');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(64, 'Viktors', 'Kleèðinskis', 1, 14, 'MASTER', 'AR', 'Krâslava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(65, 'Jâzeps', 'Kumpiòð', 1, 15, 'MASTER', 'AR', 'Krâslava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(66, 'Aleksandrs', 'Dmitrijevs', 1, 16, 'MASTER', 'AR', 'Krâslava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(67, 'Româns', 'Majevskis', 1, 17, 'MASTER', 'AR', 'Krâslava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(68, 'Vitâlijs', 'Aiðpurs', 1, NULL, 'GROUP_CHIF', 'AR', 'Krâslava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(69, 'Juris', 'Gauja', 1, 83, 'MASTER', 'RR', 'Kuldîga');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(70, 'Anrijs', 'Gârbens', 1, 84, 'MASTER', 'RR', 'Kuldîga');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(71, 'Juris', 'Dureika', 1, 85, 'MASTER', 'RR', 'Kuldîga');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(72, 'Andis', 'Balandîns', 1, NULL, 'GROUP_CHIF', 'RR', 'Kuldîga');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(73, 'Agnis', 'Krûmiòð', 1, 32, 'MASTER', 'CR', 'Íekava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(74, 'Egils', 'Stepanoviès', 1, 33, 'MASTER', 'CR', 'Íekava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(75, 'Andis', 'Kânbergs', 1, 34, 'MASTER', 'CR', 'Íekava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(76, 'Ints', 'Zariòð', 1, NULL, 'GROUP_CHIF', 'CR', 'Íekava');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(77, 'Gatis', 'Trankalis', 1, 74, 'MASTER', 'RR', 'Liepâja');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(78, 'Mâris', 'Usiks', 1, 75, 'MASTER', 'RR', 'Liepâja');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(79, 'Andrejs', 'Mihailovs', 1, 76, 'MASTER', 'RR', 'Liepâja');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(80, 'Gunârs', 'Putris', 1, 77, 'MASTER', 'RR', 'Liepâja');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(81, 'Niklâvs', 'Kerve', 1, NULL, 'GROUP_CHIF', 'RR', 'Liepâja');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(82, 'Dainis', 'Homko', 1, 135, 'MASTER', 'ZR', 'Limbaþi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(83, 'Zintis', 'Pçtersons', 1, 136, 'MASTER', 'ZR', 'Limbaþi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(84, 'Juris', 'Kalniòð', 1, 137, 'MASTER', 'ZR', 'Limbaþi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(85, 'Dainis', 'Sokolovskis', 1, 141, 'MASTER', 'ZR', 'Limbaþi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(86, 'Juris', 'Paeglis', 1, NULL, 'GROUP_CHIF', 'ZR', 'Limbaþi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(87, 'Ilmârs', 'Þogota', 1, 23, 'MASTER', 'AR', 'Ludza');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(88, 'Jevgeòijs', 'Stukâns', 1, 24, 'MASTER', 'AR', 'Ludza');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(89, 'Anatolijs', 'Anisimovs', 1, 25, 'MASTER', 'AR', 'Ludza');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(90, 'Alina', 'Koblenca', 1, 26, 'MASTER', 'AR', 'Ludza');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(91, 'Jânis', 'Vanags', 1, NULL, 'GROUP_CHIF', 'AR', 'Ludza');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(92, 'Imants', 'Lapiòð', 1, 106, 'MASTER', 'ZAR', 'Madona');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(93, 'Antons', 'Plataès', 1, 107, 'MASTER', 'ZAR', 'Madona');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(94, 'Igors', 'Dudko', 1, 108, 'MASTER', 'ZAR', 'Madona');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(95, 'Ervîns', 'Pauliòð', 1, 109, 'MASTER', 'ZAR', 'Madona');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(96, 'Jânis', 'Grinfelds', 1, NULL, 'GROUP_CHIF', 'ZAR', 'Madona');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(97, 'Vladimirs', 'Lavrenovs', 1, 40, 'MASTER', 'CR', 'Ogre');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(98, 'Ìirts', 'Perkevics', 1, 41, 'MASTER', 'CR', 'Ogre');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(99, 'Mârtiòð', 'Paegle', 1, 42, 'MASTER', 'CR', 'Ogre');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(100, 'Artûrs', 'Ðmats', 1, 43, 'MASTER', 'CR', 'Ogre');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(101, 'Andris', 'Millers', 1, NULL, 'GROUP_CHIF', 'CR', 'Ogre');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(102, 'Âris', 'Baumgarts', 1, 36, 'MASTER', 'CR', 'Piejûra');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(103, 'Juris', 'Liepiòð', 1, 37, 'MASTER', 'CR', 'Piejûra');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(104, 'Guntars', 'Orlovskis', 1, 38, 'MASTER', 'CR', 'Piejûra');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(105, 'Artûrs', 'Ancâns', 1, NULL, 'GROUP_CHIF', 'CR', 'Piejûra');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(106, 'Uldis', 'Ûdrasols', 1, 19, 'MASTER', 'AR', 'Preiïi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(107, 'Juris', 'Berzinieks', 1, 20, 'MASTER', 'AR', 'Preiïi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(108, 'Gustavs', 'Lukjanskis', 1, 21, 'MASTER', 'AR', 'Preiïi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(109, 'Jânis', 'Vosorovs', 1, NULL, 'GROUP_CHIF', 'AR', 'Preiïi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(110, 'Sergejs', 'Èernobrovs', 1, 8, 'MASTER', 'AR', 'Rçzekne');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(111, 'Ainârs', 'Arcihovskis', 1, 9, 'MASTER', 'AR', 'Rçzekne');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(112, 'Artemijs', 'Novikovs', 1, 10, 'MASTER', 'AR', 'Rçzekne');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(113, 'Juris', 'Juðkeviès', 1, 11, 'MASTER', 'AR', 'Rçzekne');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(114, 'Vadims', 'Stâmers', 1, 12, 'MASTER', 'AR', 'Rçzekne');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(115, 'Viktors', 'Þukovs', 1, NULL, 'GROUP_CHIF', 'AR', 'Rçzekne');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(116, 'Kristaps', 'Kerve', 1, NULL, 'DEPARTMENT_CHIF', 'RR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(117, 'Dace', 'Oðeniece', 1, 87, 'MASTER', 'RR', 'Saldus');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(118, 'Oskars', 'Zandbergs', 1, 88, 'MASTER', 'RR', 'Saldus');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(119, 'Armands', 'Vinceviès', 1, 89, 'MASTER', 'RR', 'Saldus');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(120, 'Ojârs', 'Âbelnieks', 1, NULL, 'GROUP_CHIF', 'RR', 'Saldus');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(121, 'Kaspars', 'Liepiòð', 1, 132, 'MASTER', 'ZR', 'Smiltene');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(122, 'Dzintars', 'Fabiâns', 1, 133, 'MASTER', 'ZR', 'Smiltene');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(123, 'Ivars', 'Pavârnieks', 1, 140, 'MASTER', 'ZR', 'Smiltene');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(124, 'Jânis', 'Norkus', 1, NULL, 'GROUP_CHIF', 'ZR', 'Smiltene');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(125, 'Mâris', 'Uplejs', 1, 66, 'MASTER', 'DR', 'Talsi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(126, 'Juris', 'Rutkis', 1, 67, 'MASTER', 'DR', 'Talsi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(127, 'Ìirts', 'Zanders', 1, 68, 'MASTER', 'DR', 'Talsi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(128, 'Gatis', 'Priede-Priedîtis', 1, 69, 'MASTER', 'DR', 'Talsi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(129, 'Egils', 'Valbergs', 1, NULL, 'GROUP_CHIF', 'DR', 'Talsi');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(130, 'Jânis', 'Âdamsons', 1, 71, 'MASTER', 'DR', 'Tukums');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(131, 'Andris', 'Veiriòð', 1, 72, 'MASTER', 'DR', 'Tukums');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(132, 'Rûdolfs', 'Veigulis', 1, 147, 'MASTER', 'DR', 'Tukums');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(133, 'Vitâlijs', 'Kondratjevs', 1, 148, 'MASTER', 'DR', 'Tukums');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(134, 'Normunds', 'Marovskis', 1, NULL, 'GROUP_CHIF', 'DR', 'Tukums');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(135, 'Didzis', 'Krûskops', 1, 120, 'MASTER', 'ZR', 'Valmiera');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(136, 'Raivis', 'Âbele', 1, 121, 'MASTER', 'ZR', 'Valmiera');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(137, 'Alvils', 'Mucenieks', 1, 122, 'MASTER', 'ZR', 'Valmiera');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(138, 'Artis', 'Deksnis', 1, 144, 'MASTER', 'ZR', 'Valmiera');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(139, 'Artis', 'Kïaviòð', 1, NULL, 'GROUP_CHIF', 'ZR', 'Valmiera');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(140, 'Intars', 'Grinbergs', 1, 91, 'MASTER', 'RR', 'Ventspils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(141, 'Andris', 'Serþants', 1, 92, 'MASTER', 'RR', 'Ventspils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(142, 'Gints', 'Reinbergs', 1, 93, 'MASTER', 'RR', 'Ventspils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(143, 'Rolands', 'Agafonovs', 1, NULL, 'GROUP_CHIF', 'RR', 'Ventspils');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(144, 'Dzintars', 'Stradiòð', 1, 116, 'DEPARTMENT_CHIF', 'ZAR', 'Aizkraukle');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(145, 'Visvaldis', 'Ozoliòð', 1, NULL, 'DEPARTMENT_CHIF', 'ZR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(146, 'Rita', 'Staðulâne', 1, NULL, 'ENGINEER', 'AR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(147, 'Artûrs', 'Vilcâns', 1, NULL, 'ENGINEER', 'CR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(148, 'Valerijs', 'Mikutis', 1, NULL, 'ENGINEER', 'CR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(149, 'Aleksandrs', 'Ðapovalovs', 1, NULL, 'ENGINEER', 'DR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(150, 'Vilnis', 'Siliòð', 1, NULL, 'ENGINEER', 'DR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(151, 'Ivars', 'Strelçviès', 1, NULL, 'EKSPOATATION_ENGINEER', 'RR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(152, 'Raivis', 'Ìenerâlis', 1, NULL, 'ENGINEER', 'RR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(153, 'Aldis', 'Anzons', 1, NULL, 'ENGINEER', 'ZAR', 'Aizkraukle');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(154, 'Uldis', 'Krûmiòð', 1, NULL, 'ENGINEER', 'ZAR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(155, 'Andis', 'Muðperts', 1, NULL, 'ENGINEER', 'ZR', 'Ekspluatâcijas daïa');
INSERT INTO KL_SASKANOTAJI (SLTT_ID, SLTT_VARDS, SLTT_UZVARDS, SLTT_IR_AKTIVS, SLTT_KEDI_ID, SLTT_POSITION, SLTT_REGIONS, SLTT_KEDI_SECTION) VALUES(156, 'Oskars', 'Vîtols', 1, NULL, 'ENGINEER', 'ZR', 'Ekspluatâcijas daïa');


 INSERT INTO  `KL_REF_KODI` (
`KRFK_ID` ,
`KRFK_NOSAUKUMS` ,
`KRFK_VERTIBA` ,
`KRFK_NOZIME`
)
VALUES (NULL ,  'STATUS',  'TOPAY',  'Nodots apmaksai' );

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES ('TOPAY', 'Nodot apmaksai'),
('WARNING_TOPAY', 'Vai tieðâm vçlaties `Nodot apmaksai` aktu?');

-- 08.06.2012
UPDATE `KL_REF_KOLONNAS` SET `KLKL_TITLE` = 'ED nodaïa' WHERE
`KLKL_CATALOG` IN ('KL_KALKULACIJA', 'KL_KALKULACIJA_TRASE') AND
`KLKL_COLUMN` = 'KKAL_KEDI_SECTION';

DELETE FROM `FMK_MESSAGES` WHERE `CODE` = 'TRASE_KALCULATION';
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)   VALUES  ('TRASE_KALCULATION', 'Trases kalkulâcijas');

UPDATE `FMK_MESSAGES` SET `TEXT` = 'Darbu izpilde saskaòâ ar vienoðanos Nr.' WHERE `CODE` = 'WORK_DONE_AGREEMENT_NO'      ;

UPDATE `FMK_MESSAGES` SET `TEXT` = 'PAKALPOJUMA PIEÒEMÐANAS - NODOÐANAS AKTA SAGATAVE' WHERE `CODE` = 'TRASE_ACT_HEADER4'      ;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)   VALUES  ('REQUIREMENTS_CALCULATION_TR',
'<table cellpadding="3" cellspacing="0" border="1" width="100%">
        <tr>
           <th>Kolonas dati</th>
           <th>Obligâts</th>
           <th>Kolonas datu apraksts</th>
        </tr>
        <tr>
            <td>Grupas kods</td>
            <td>+</td>
            <td>Kalkulâcijas grupas kods. Var saturçt tikai sekojoðus simbolus `a`-`z`, `A`-`Z`, `0`-`9`. Maksimâli 5 simboli. </td>
        </tr>
        <tr>
            <td>Kalkulâcijas ðifrs</td>
            <td>+</td>
            <td>Kalkulâcijas ðifrs. Var saturçt tikai sekojoðus simbolus `0`-`9`. Maksimâli 5 simboli.</td>
        </tr>
        <tr>
            <td>Kalkulâcijas nosaukums</td>
            <td>+</td>
            <td>Kalkulâcijas nosaukums. Maksimâli 150 simboli.</td>
        </tr>
        <tr>
            <td>Mçrvienîba</td>
            <td>+</td>
            <td>Kalkulâcijas mçrvienîba. Maksimâli 15 simboli. </td>
        </tr>

        <tr>
            <td>Fiziskais râdîtâjs</td>
            <td>+</td>
            <td>Fiziska râdîtâja pazime. Var saturçt tikai sekojoðus simbolus [`1`-`9`]`z` vai [`1`-`11`]`v`. Maksimâli 3 simboli. </td>
        </tr>
       	<tr>
            <td>Darbuzòçmçjs</td>
            <td>+</td>
            <td>Darbuzòçmçja identifikators. Cipars.</td>
        </tr>
        <tr>
            <td>Lîguma Nr.</td>
            <td>+</td>
            <td>Vispârîgâs vienoðanâs nr. Maksimâli 20 simboli.</td>
        </tr>
	<tr>
            <td>ED nodaïa</td>
            <td>+</td>
            <td>ED nodaïas nosaukums. Maksimâli 250 simboli. </td>
        </tr>
	<tr>
            <td>Plâna cena</td>
            <td>+</td>
            <td>Plâna darbu cena. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
	<tr>
            <td>Neplâna cena</td>
            <td>+</td>
            <td>Neplâna darbu cena. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
      <tr>
            <td>Stihijas kalkul.</td>
            <td>+</td>
            <td>Stihijas kalkul. Cipars formatâ  [0/1]</td>
        </tr>
      <tr>
            <td>Apraksts</td>
            <td>-</td>
            <td>Kalkulâcijas apraksts. Maksimâli 2000 simboli. </td>
        </tr>
       </table>');


---
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)   VALUES  ('REQUIREMENTS_HARMONIZED',
'<table cellpadding="3" cellspacing="0" border="1" width="100%">
        <tr>
           <th>Kolonas dati</th>
           <th>Obligâts</th>
           <th>Kolonas datu apraksts</th>
        </tr>
        <tr>
            <td>ÌIS iecirkòa Nr.</td>
            <td>+</td>
            <td>ED iecirkòa Nr. Var saturçt tikai sekojoðus simbolus `0`-`9`. Maksimâli 5 simboli. </td>
        </tr>
        <tr>
            <td>Vârds</td>
            <td>+</td>
            <td>Saskaòotaja vârds. Maksimâli 30 simboli.</td>
        </tr>
        <tr>
            <td>Uzvârds</td>
            <td>+</td>
            <td>Saskaòotaja uzvârds. Maksimâli 30 simboli.</td>
        </tr>
        <tr>
            <td>Amats</td>
            <td>+</td>
            <td>Saskaòotaja amats. Maksimâli 50 simboli. </td>
        </tr>

       </table>');

INSERT INTO  `KL_REF_KODI` (
`KRFK_ID` ,
`KRFK_NOSAUKUMS` ,
`KRFK_VERTIBA` ,
`KRFK_NOZIME`
)
VALUES (NULL ,  'IMPORTS',  'HARMONIZED',  'Saskaòotâji' );

-- 14.08.2013
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('EXPORT_ACT_APOVE', 'Aktu apstiprinâja');

-- 21.08.2013
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('TRASE_ACT_HEADER5', 'Par traðu attîrîðanu no apauguma izpildîto darbu pieòemðanu');
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('ST_REG_NR', '40003857687');
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('WORKS_AND_TERITORY', 'Darbîbas un atbildîbas teritorija');
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('SIGNATURE', 'Paraksts');

-- 21.10.2013
ALTER TABLE `KL_SASKANOTAJI` ADD `SLTT_ED_IECIKNIS` varchar(250) collate utf8_latvian_ci NOT NULL DEFAULT 'ekspluatâcijas daïa' ;
INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES ( 'SLTT_ED_IECIKNIS', 'Struktûrvienîba', 'KL_SASKANOTAJI', '0' );

UPDATE `FMK_MESSAGES` SET `TEXT` = '<table cellpadding="3" cellspacing="0" border="1" width="100%">
        <tr>
           <th>Kolonas dati</th>
           <th>Obligâts</th>
           <th>Kolonas datu apraksts</th>
        </tr>
        <tr>
            <td>ÌIS iecirkòa Nr.</td>
            <td>+</td>
            <td>ED iecirkòa Nr. Var saturçt tikai sekojoðus simbolus `0`-`9`. Maksimâli 5 simboli. </td>
        </tr>
        <tr>
            <td>Vârds</td>
            <td>+</td>
            <td>Saskaòotaja vârds. Maksimâli 30 simboli.</td>
        </tr>
        <tr>
            <td>Uzvârds</td>
            <td>+</td>
            <td>Saskaòotaja uzvârds. Maksimâli 30 simboli.</td>
        </tr>
        <tr>
            <td>Amats</td>
            <td>+</td>
            <td>Saskaòotaja amats. Maksimâli 50 simboli. </td>
        </tr>
        <tr>
            <td>Struktûrvienîba</td>
            <td>+</td>
            <td>Nodaïas nosaukums. Maksimâli 250 simboli. </td>
        </tr>
       </table>'
WHERE `CODE` =  'REQUIREMENTS_HARMONIZED'  ;


INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('PRINT_WORK_TITLE', 'Darba nosaukums (izdrukâm)');
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('REGIONS', 'Reìioni');

CREATE TABLE IF NOT EXISTS `KL_REGIONI` (
  `REGI_ID` int(11) NOT NULL auto_increment,
  `REGI_KODS` char(5) collate utf8_latvian_ci NOT NULL,
  `REGI_NOSAUKUMS` varchar(250) collate utf8_latvian_ci NOT NULL,
  `REGI_IR_AKTIVS` tinyint(1) default '1',
  PRIMARY KEY  (`REGI_ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_latvian_ci AUTO_INCREMENT=1 ;


INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES ( 'REGI_KODS', 'Kods', 'KL_REGIONI', '1' ),
( 'REGI_NOSAUKUMS', 'Nosaukums', 'KL_REGIONI', '0' ),
( 'REGI_IR_AKTIVS', 'Ir aktîvs (1/0)', 'KL_REGIONI', '0' );

-- 21.11.2013
UPDATE `FMK_MESSAGES` SET `TEXT` = 'KvikStepa kods ir sastâdîts nepareizi. Koda ievades formâts %s-xxxxxxx, kur  x-skaitlis' WHERE `CODE` ='ERROR_ACT_NUM_POSTFIX' ;

--18,02,2014
INSERT INTO  `KL_REF_KODI` (
`KRFK_ID` ,
`KRFK_NOSAUKUMS` ,
`KRFK_VERTIBA` ,
`KRFK_NOZIME`
)
VALUES (NULL ,  'REGIONNAME',  'PR',  'Pierîgas' );

UPDATE `FMK_MESSAGES` SET `TEXT` = 'aprîlis' WHERE `ID` = 400 LIMIT 1;
UPDATE `FMK_MESSAGES` SET `TEXT` = 'augusts' WHERE `ID` = 404 LIMIT 1;
UPDATE `FMK_MESSAGES` SET `TEXT` = 'decembris' WHERE `ID` = 408 LIMIT 1;
UPDATE `FMK_MESSAGES` SET `TEXT` = 'februâris' WHERE `ID` = 398 LIMIT 1;
UPDATE `FMK_MESSAGES` SET `TEXT` = 'janvâris' WHERE `ID` = 397 LIMIT 1;
UPDATE `FMK_MESSAGES` SET `TEXT` = 'jûlijs' WHERE `ID` = 403 LIMIT 1;
UPDATE `FMK_MESSAGES` SET `TEXT` = 'jûnijs' WHERE `ID` = 402 LIMIT 1;
UPDATE `FMK_MESSAGES` SET `TEXT` = 'maijs' WHERE `ID` = 401 LIMIT 1;
UPDATE `FMK_MESSAGES` SET `TEXT` = 'marts' WHERE `ID` = 399 LIMIT 1;
UPDATE `FMK_MESSAGES` SET `TEXT` = 'novembris' WHERE `ID` = 407 LIMIT 1;
UPDATE `FMK_MESSAGES` SET `TEXT` = 'oktobris' WHERE `ID` = 406 LIMIT 1;
UPDATE `FMK_MESSAGES` SET `TEXT` = 'septembris' WHERE `ID` = 405 LIMIT 1;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES ('EXP_OUNER_CHIF', 'nodaïas vadîtâjs'),
('EXP_OUNER_ENGENEER', 'elektroietaiðu ekspluatâcijas inþenieris'),
('EXP_OUNER_OPERATING_PART', 'Daïas vadîtjs');

-- 05.06.2014
--ALTER TABLE `KL_AKTA_VEIDS` DROP `KAKV_WORK_TITLE` ;
--DELETE FROM `KL_REF_KOLONNAS` WHERE `KLKL_COLUMN` =  'KAKV_WORK_TITLE';

ALTER TABLE `AKTI` ADD `RAKT_WORK_TITLE` varchar(250) collate utf8_latvian_ci  ;

--03.07.2014 NEW CONTRACT NO
CREATE TABLE IF NOT EXISTS `KL_CONTRACT` (
  `KCNT_ID` int(11) NOT NULL auto_increment,
  `KCNT_KWOI_KODS` varchar(13) collate utf8_latvian_ci NOT NULL,
  `KCNT_VV_NUMBER` varchar(20) collate utf8_latvian_ci NOT NULL,
  `KCNT_IR_AKTIVS` tinyint(1) default '1',
  `KCNT_IR_TRASE` int(1) default 0,
  PRIMARY KEY  (`KCNT_ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_latvian_ci AUTO_INCREMENT=1 ;


INSERT INTO `KL_CONTRACT` (`KCNT_KWOI_KODS`, `KCNT_VV_NUMBER`)  (SELECT `KWOI_KODS`, `KWOI_VV_NUMBER` FROM `KL_WORK_OWNERS`) ;
-- the same contract no for trase
INSERT INTO `KL_CONTRACT` (`KCNT_KWOI_KODS`, `KCNT_VV_NUMBER`, `KCNT_IR_TRASE`)  (SELECT `KWOI_KODS`, `KWOI_VV_NUMBER`, 1 FROM `KL_WORK_OWNERS`) ;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES ('ERROR_CONTRACT_EXIST', 'Tâds lîguma numurs jau eksistç.'),
('ERROR_CONTRACT_IS_USED', 'Lîguma numurs ir piesaistîts pie cita objekta');

ALTER TABLE `KL_KALKULACIJA`  ADD  `KKAL_VV_NUMBER` varchar(20) ;
ALTER TABLE `KL_KALKULACIJA_TRASE`  ADD  `KKAL_VV_NUMBER` varchar(20) ;
ALTER TABLE `AKTI`  ADD  `RAKT_VV_NUMBER` varchar(20) ;

UPDATE `KL_KALKULACIJA` SET `KKAL_VV_NUMBER` =
    (SELECT `KWOI_VV_NUMBER` FROM `KL_WORK_OWNERS` WHERE `KWOI_KODS` = `KKAL_KWOI_KODS`) ;

UPDATE `KL_KALKULACIJA_TRASE` SET `KKAL_VV_NUMBER` =
    (SELECT `KWOI_VV_NUMBER` FROM `KL_WORK_OWNERS` WHERE `KWOI_KODS` = `KKAL_KWOI_KODS`) ;

UPDATE `AKTI` SET `RAKT_VV_NUMBER` =
    (SELECT `KWOI_VV_NUMBER` FROM `KL_WORK_OWNERS` WHERE `KWOI_KODS` = `RAKT_KWOI_KODS`) ;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES ('WARNING_DELETE_CONTRACT', 'Vai tieðâm dzçst lîguma numuru?') ;

DELETE FROM `KL_REF_KOLONNAS` WHERE `KLKL_ID` = 81 LIMIT 1;
DELETE FROM `KL_REF_KOLONNAS` WHERE `KLKL_ID` = 93 LIMIT 1;

UPDATE `FMK_MESSAGES` SET `TEXT` = '<table cellpadding="3" cellspacing="0" border="1" width="100%">
        <tr>
           <th>Kolonas dati</th>
           <th>Obligâts</th>
           <th>Kolonas datu apraksts</th>
        </tr>
        <tr>
            <td>Grupas kods</td>
            <td>+</td>
            <td>Kalkulâcijas grupas kods. Var saturçt tikai sekojoðus simbolus `a`-`z`, `A`-`Z`, `0`-`9`. Maksimâli 5 simboli. </td>
        </tr>
        <tr>
            <td>Kalkulâcijas ðifrs</td>
            <td>+</td>
            <td>Kalkulâcijas ðifrs. Unikâls. Var saturçt tikai sekojoðus simbolus `0`-`9`. Maksimâli 5 simboli.</td>
        </tr>
        <tr>
            <td>Kalkulâcijas nosaukums</td>
            <td>+</td>
            <td>Kalkulâcijas nosaukums. Maksimâli 150 simboli.</td>
        </tr>
        <tr>
            <td>Mçrvienîba</td>
            <td>+</td>
            <td>Kalkulâcijas mçrvienîba. Maksimâli 15 simboli. </td>
        </tr>
         <tr>
            <td>Apraksts</td>
            <td>-</td>
            <td>Kalkulâcijas apraksts. Maksimâli 2000 simboli. </td>
        </tr>
        <tr>
            <td>Fiziskais râdîtâjs</td>
            <td>-</td>
            <td>Fiziska râdîtâja pazime. Var saturçt tikai sekojoðus simbolus [`2`-`9`]`z` vai [`2`-`11`]`v`. Maksimâli 3 simboli. </td>
        </tr>
       	<tr>
            <td>Darbuzòçmçjs</td>
            <td>-</td>
            <td>Darbuzòçmçja identifikators. Cipars.</td>
        </tr>
<tr>
            <td>Lîguma Nr.</td>
            <td>+</td>
            <td>Vispârîgâs vienoðanâs nr. Maksimâli 20 simboli.</td>
        </tr>
	<tr>
            <td>ED nodaïa</td>
            <td>-</td>
            <td>ED nodaïas nosaukums. Maksimâli 250 simboli. </td>
        </tr>
	<tr>
            <td>Plâna cena</td>
            <td>-</td>
            <td>Plâna darbu cena. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
	<tr>
            <td>Neplâna cena</td>
            <td>-</td>
            <td>Neplâna darbu cena. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
        <tr>
            <td>Fiz.râd. koefic.</td>
            <td>+</td>
            <td>Fiz.râd. koefic. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
<tr>
            <td>Stihijas kalkul.</td>
            <td>+</td>
            <td>Stihijas kalkul. Cipars formatâ  [0/1]</td>
        </tr>


        <tr>
            <td>1</td>
            <td>-</td>
            <td>Papildus kolonna. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
        <tr>
            <td>2</td>
            <td>-</td>
            <td>Papildus kolonna. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
        <tr>
            <td>3</td>
            <td>-</td>
            <td>Papildus kolonna. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
        <tr>
            <td>4</td>
            <td>-</td>
            <td>Papildus kolonna. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
        <tr>
            <td>5</td>
            <td>-</td>
            <td>Papildus kolonna. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
        <tr>
            <td>6</td>
            <td>-</td>
            <td>Papildus kolonna. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
        <tr>
            <td>7</td>
            <td>-</td>
            <td>Papildus kolonna. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
        <tr>
            <td>8</td>
            <td>-</td>
            <td>Papildus kolonna. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
        <tr>
            <td>9</td>
            <td>-</td>
            <td>Papildus kolonna. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
        <tr>
            <td>10</td>
            <td>-</td>
            <td>Papildus kolonna. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
       </table>'
WHERE `CODE` = 'REQUIREMENTS_CALCULATION' ;

ALTER TABLE `KL_MMS_DARBI`  ADD  `KMSD_VV_NUMBER` varchar(20) ;
UPDATE `KL_MMS_DARBI` SET `KMSD_VV_NUMBER` =
    (SELECT `KWOI_VV_NUMBER` FROM `KL_WORK_OWNERS` WHERE `KWOI_KODS` = `KMSD_KWOI_KODS`) ;

UPDATE `FMK_MESSAGES` SET `TEXT` = '<table cellpadding="3" cellspacing="0" border="1" width="100%">
        <tr>
           <th>Kolonas dati</th>
           <th>Obligâts</th>
           <th>Kolonas datu apraksts</th>
        </tr>
        <tr>
            <td>Kods</td>
            <td>+</td>
            <td>MMS darba kods. Maksimâli 150 simboli. </td>
        </tr>
        <tr>
            <td>Cilvekstundas</td>
            <td>+</td>
            <td>Cipars formatâ [xxxxx.xx]. </td>
        </tr>
        <tr>
            <td>Materiâla izmaksas</td>
            <td>+</td>
            <td>Cipars formatâ [xxxxx.xx]. </td>
        </tr>
        <tr>
            <td>Ceturksnis</td>
            <td>+</td>
            <td>Atïautas vçrtîbas: 1, 2, 3, 4. </td>
        </tr>
        <tr>
            <td>Gads</td>
            <td>+</td>
            <td>Cipars formatâ [xxxx]. </td>
        </tr>
        <tr>
            <td>Problemobjekts</td>
            <td>+</td>
            <td>Atïautas vçrtîbas: 0, 1 </td>
        </tr>
        <tr>
            <td>Struktûrvienîbas kods</td>
            <td>+</td>
            <td>Cipars formatâ [xxxx]. </td>
        </tr>
<tr>
            <td>Darbuzòçmçjs</td>
            <td>-</td>
            <td>Darbuzòçmçja identifikators. Cipars.</td>
        </tr>
        <tr>
            <td>Lîguma Nr.</td>
            <td>+</td>
            <td>Vispârîgâs vienoðanâs nr. Maksimâli 20 simboli.</td>
        </tr>
<tr>
            <td>DU trases</td>
            <td>+</td>
            <td>Atïautas vçrtîbas: 0, 1 </td>
        </tr>
        <tr><td>1z</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>2z</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>3z</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>4z</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>5z</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>6z</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>7z</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>8z</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>9z</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>1v</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>2v</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>3v</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>4v</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>5v</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>6v</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>7v</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>8v</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>9v</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>10v</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
        <tr><td>11v</td><td>+</td><td>Cipars formatâ [xxxxx.xx].</td></tr>
       </table>'
WHERE `CODE` = 'REQUIREMENTS_MMS_WORKS' ;
ALTER TABLE `SEARCH_CRITERIA`  ADD  `CONTRACT` varchar(20) ;

ALTER TABLE `KL_CONTRACT` ADD `KCNT_SECTION` varchar(250) collate utf8_latvian_ci NOT NULL;

-- 01.10.2014
ALTER TABLE `LIETOTAJI` ADD `RLTT_IR_LIGUMS` INT( 1 ) NOT NULL DEFAULT '0' AFTER `RLTT_IR_TRASE` ;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)  VALUES ('CONTRACT_USER', 'Pçc lîguma');

INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES (
'RLTT_IR_LIGUMS', 'Pçc lîguma (1/0)', 'KL_LIETOTAJI_DU', '0'
);

UPDATE `LIETOTAJI` SET `RLTT_IR_LIGUMS` = 1 WHERE `RLTT_IR_TRASE` <> 1;

UPDATE `FMK_MESSAGES` SET  `TEXT` = 'Daïas vadîtâjs' WHERE `CODE` =  'EXP_OUNER_OPERATING_PART';
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('SUPORT_ACT_HEADER5', 'Par uzturçðanas remonta  darbu pieòemðanu');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('REPORT_DEPARTMENT', 'ekspluatâcijas daïa');

INSERT INTO `KL_REGIONI` (`REGI_ID`, `REGI_KODS`, `REGI_NOSAUKUMS`, `REGI_IR_AKTIVS`) VALUES
(1, 'AR', 'Austrumu', 1),
(2, 'CR', 'Centrâlais', 1),
(3, 'DR', 'Dienvidu', 1),
(4, 'RR', 'Rietumu', 1),
(5, 'ZAR', 'Ziemeïaustrumu', 1),
(6, 'ZR', 'Ziemeïu', 1),
(7, 'PR', 'Pierîgas', 1);

UPDATE `FMK_MESSAGES` SET `text` = '<table cellpadding="3" cellspacing="0" border="1" width="100%">
        <tr>
           <th>Kolonas dati</th>
           <th>Obligâts</th>
           <th>Kolonas datu apraksts</th>
        </tr>
        <tr>
            <td>Grupas kods</td>
            <td>+</td>
            <td>Kalkulâcijas grupas kods. Var saturçt tikai sekojoðus simbolus `a`-`z`, `A`-`Z`, `0`-`9`. Maksimâli 5 simboli. </td>
        </tr>
        <tr>
            <td>Kalkulâcijas ðifrs</td>
            <td>+</td>
            <td>Kalkulâcijas ðifrs. Var saturçt tikai sekojoðus simbolus `0`-`9`. Maksimâli 5 simboli.</td>
        </tr>
        <tr>
            <td>Kalkulâcijas nosaukums</td>
            <td>+</td>
            <td>Kalkulâcijas nosaukums. Maksimâli 150 simboli.</td>
        </tr>
        <tr>
            <td>Mçrvienîba</td>
            <td>+</td>
            <td>Kalkulâcijas mçrvienîba. Maksimâli 15 simboli. </td>
        </tr>

        <tr>
            <td>Fiziskais râdîtâjs</td>
            <td>+</td>
            <td>Fiziska râdîtâja pazime. Var saturçt tikai sekojoðus simbolus [`1`-`9`]`z` vai [`1`-`11`]`v`. Maksimâli 3 simboli. </td>
        </tr>
       	<tr>
            <td>Darbuzòçmçjs</td>
            <td>+</td>
            <td>Darbuzòçmçja identifikators. Cipars.</td>
        </tr>
        <tr>
            <td>Lîguma Nr.</td>
            <td>+</td>
            <td>Vispârîgâs vienoðanâs nr. Maksimâli 20 simboli.</td>
        </tr>
	<tr>
            <td>ED nodaïa</td>
            <td>+</td>
            <td>ED nodaïas nosaukums. Maksimâli 250 simboli. </td>
        </tr>
	<tr>
            <td>Plâna cena</td>
            <td>+</td>
            <td>Plâna darbu cena. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
	<tr>
            <td>Neplâna cena</td>
            <td>+</td>
            <td>Neplâna darbu cena. Cipars formatâ [xxxxx.xx]. </td>
        </tr>
<tr>
            <td>Stihijas kalkul.</td>
            <td>+</td>
            <td>Stihijas kalkul. Cipars formatâ  [0/1]</td>
        </tr>
      <tr>
            <td>Apraksts</td>
            <td>-</td>
            <td>Kalkulâcijas apraksts. Maksimâli 2000 simboli. </td>
        </tr>
       </table>'
WHERE `code` LIKE 'REQUIREMENTS_CALCULATION_TR';

--

UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Krâslavas nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Krâslava' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Preiïu nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Preiïi' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Ludzas nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Ludza' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Daugavpils nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Daugavpils' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Rçzeknes nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Rçzekne' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Bauskas nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Bauska' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Jelgavas nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Jelgava' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Dobeles nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Dobele' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Talsu nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Talsi' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Tukuma nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Tukums' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Juglas nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Jugla' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Íekavas nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Íekava' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Piejûras nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Piejûra' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Ogres nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Ogre' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Jûrmalas nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Jûrmala' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Ventspils nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Ventspils' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Kuldîgas nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Kuldîga' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Saldus nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Saldus' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Aizputes nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Aizpute' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Liepâjas nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Liepâja' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Gulbenes nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Gulbene' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Aizkraukles nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Aizkraukle' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Balvu nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Balvi' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Madonas nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Madona' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Jçkabpils nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Jçkabpils' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Alûksnes nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Alûksne' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Limbaþu nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Limbaþi' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Cçsu nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Cçsis' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Valmieras nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Valmiera' AND `KKAL_KWOI_KODS` = '10722319';
UPDATE  `KL_KALKULACIJA` SET `KKAL_KEDI_SECTION` = 'Smiltenes nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Smiltene' AND `KKAL_KWOI_KODS` = '10722319';

-- saskaòotaji
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Krâslavas nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Krâslava';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Preiïu nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Preiïi' ;
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Ludzas nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Ludza' ;
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Daugavpils nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Daugavpils';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Rçzeknes nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Rçzekne';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Bauskas nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Bauska' ;
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Jelgavas nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Jelgava';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Dobeles nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Dobele' ;
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Talsu nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Talsi' ;
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Tukuma nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Tukums' ;
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Juglas nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Jugla' ;
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Íekavas nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Íekava' ;
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Piejûras nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Piejûra';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Ogres nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Ogre';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Jûrmalas nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Jûrmala';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Ventspils nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Ventspils';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Kuldîgas nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Kuldîga';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Saldus nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Saldus' ;
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Aizputes nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Aizpute';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Liepâjas nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Liepâja';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Gulbenes nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Gulbene';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Aizkraukles nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Aizkraukle';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Balvu nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Balvi' ;
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Madonas nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Madona' ;
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Jçkabpils nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Jçkabpils';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Alûksnes nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Alûksne';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Limbaþu nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Limbaþi';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Cçsu nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Cçsis';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Valmieras nodaïa' WHERE `SLTT_KEDI_SECTION` = 'Valmiera';
UPDATE  `KL_SASKANOTAJI` SET `SLTT_KEDI_SECTION` = 'Smiltenes nodaïa' WHERE `KKAL_KEDI_SECTION` = 'Smiltene';

Gads - 2014, 2015, 2016, ...
Mçnesis - 01, 02, 03, 04, ....
EF daïa - AE daïa, ZAE daïa, ....
EF nodaïa - Daugavpils, Rçzekne, ...
cvh - 1500, 2000, 3000, ....

CREATE TABLE IF NOT EXISTS `KL_EF_PASUTIJUMI` (
  `KEFP_ID` int(11) NOT NULL auto_increment,
  `KEFP_GADS` int(4),
  `KEFP_MENESIS` int(2),
  `KEFP_EF_DEPARTMENT` varchar(100) collate utf8_latvian_ci NOT NULL,
  `KEFP_EF_SECTION` varchar(100) collate utf8_latvian_ci NOT NULL,
  PRIMARY KEY  (`KEFP_ID`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_latvian_ci AUTO_INCREMENT=1 ;

INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES ('KEFP_GADS', 'Gads', 'KL_EF_PASUTIJUMI', '0' ),
('KEFP_MENESIS', 'Mçnesis', 'KL_EF_PASUTIJUMI', '0' ),
('KEFP_EF_DEPARTMENT', 'EF daïa', 'KL_EF_PASUTIJUMI', '1' ),
('KEFP_EF_SECTION', 'EF nodaïa', 'KL_EF_PASUTIJUMI', '0' )
;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('EF_DEPARTMENT', 'EF daïa');
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('EF_SECTION', 'EF nodaïa');
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('CVH', 'cvh');

INSERT INTO `KL_REF_KOLONNAS` (
`KLKL_COLUMN` ,
`KLKL_TITLE` ,
`KLKL_CATALOG` ,
`KLKL_IS_DEFAULT`
)
VALUES ('KEFP_CVH', 'cvh', 'KL_EF_PASUTIJUMI', '0' );

ALTER TABLE `KL_EF_PASUTIJUMI` ADD `KEFP_CVH` INT(6);

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES ('EF_ORDER_TITLE', 'EF pasûtîjums');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)   VALUES  ('REQUIREMENTS_EF_ORDER',
'<table cellpadding="3" cellspacing="0" border="1" width="100%">
        <tr>
           <th>Kolonas dati</th>
           <th>Obligâts</th>
           <th>Kolonas datu apraksts</th>
        </tr>
        <tr>
            <td>Gads</td>
            <td>+</td>
            <td>Gads. Var saturçt tikai sekojoðus simbolus `0`-`9`. Maksimâli 2 simboli. </td>
        </tr>
        <tr>
            <td>Mçnesis</td>
            <td>+</td>
            <td>Mçnesis. Var saturçt tikai sekojoðus simbolus `0`-`9`. Maksimâli 2 simboli.</td>
        </tr>
        <tr>
            <td>EF daïa</td>
            <td>+</td>
            <td>EF daïa.  Maksimâli 100 simboli.</td>
        </tr>
        <tr>
            <td>EF nodaïa</td>
            <td>+</td>
            <td>EF nodaïa. Maksimâli 100 simboli. </td>
        </tr>
        <tr>
            <td>CVH</td>
            <td>+</td>
            <td>CVH. Var saturçt tikai sekojoðus simbolus `0`-`9`. Maksimâli 6 simboli. </td>
        </tr>

       </table>');