-- Check if codes exist before inserting
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'UPLOAD_ESTIMATE' AS CODE, 'Augšuplādēt tāmi' AS TEXT) AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'UPLOAD_ESTIMATE');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'TAB_UPLOAD_STAT', 'Augšupielādes statistika') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'TAB_UPLOAD_STAT');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'ROWS', 'Rindas') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'ROWS');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'VIEW_DETAILS', 'Skatīt detaļas') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'VIEW_DETAILS');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'NO_DATA', 'Nav datu') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'NO_DATA');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'STATUS_SAVED', 'Saglabāts') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'STATUS_SAVED');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'STATUS_EXISTS', 'Eksistē') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'STATUS_EXISTS');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'STATUS_NOT_FOUND', 'Nav atrasts') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'STATUS_NOT_FOUND');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'NO_WORK_TYPE', 'Bez darba veida') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'NO_WORK_TYPE');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'NO_TITLE', 'Nav nosaukuma') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'NO_TITLE');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'STATUS_UNKNOWN', 'Nezināms') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'STATUS_UNKNOWN');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'ESTIMATE_STATISTICS', 'Tāmes statistika') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'ESTIMATE_STATISTICS');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'ACT_LABEL', 'Akts:') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'ACT_LABEL');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'FILE_LABEL', 'Fails:') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'FILE_LABEL');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'DATE_LABEL', 'Datums:') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'DATE_LABEL');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'STATUS', 'Statuss') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'STATUS');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'ERROR_CREATING_EXCEL', 'Kļūda izveidojot Excel failu.') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'ERROR_CREATING_EXCEL');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'ERROR_ESTIMATE_FILE_NOT_FOUND', 'Tāmes fails nav atrasts.') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'ERROR_ESTIMATE_FILE_NOT_FOUND');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'ERROR_ESTIMATE_ID_NOT_PROVIDED', 'Nav norādīts tāmes ID.') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'ERROR_ESTIMATE_ID_NOT_PROVIDED');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'FILE_UPLOADED_SUCCESSFULLY', 'Fails ir veiksmīgi augšupielādēts un apstrādāts. Tāmes ID:') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'FILE_UPLOADED_SUCCESSFULLY');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'TOTAL_ROWS_COUNT', 'Kopā rindu:') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'TOTAL_ROWS_COUNT');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'WORK_ROWS_LABEL', 'Darbu rindas:') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'WORK_ROWS_LABEL');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'MATERIAL_ROWS_LABEL', 'Materiālu rindas:') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'MATERIAL_ROWS_LABEL');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'SAVED_TO_WORKS', 'Saglabāts DARBI:') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'SAVED_TO_WORKS');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'SAVED_TO_MATERIALS', 'Saglabāts MATERIALI:') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'SAVED_TO_MATERIALS');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'ALREADY_EXISTS_LABEL', 'Jau eksistē:') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'ALREADY_EXISTS_LABEL');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'NOT_FOUND_IN_CATALOG_LABEL', 'Nav atrasts katalogā:') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'NOT_FOUND_IN_CATALOG_LABEL');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'SKIPPED_ROWS_LABEL', 'Izlaistas rindas:') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'SKIPPED_ROWS_LABEL');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'IGNORE_TEXT_WORK_COSTS', 'Darbu izmaksas') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'IGNORE_TEXT_WORK_COSTS');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
SELECT * FROM (SELECT 'IGNORE_TEXT_MATERIAL_COSTS', 'Materiālu izmaksas') AS tmp
WHERE NOT EXISTS (SELECT CODE FROM `FMK_MESSAGES` WHERE CODE = 'IGNORE_TEXT_MATERIAL_COSTS');

CREATE TABLE estimate_files (
	`ESTM_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`ESTM_NAME` VARCHAR(250) NULL,
	`ESTM_DATE` DATETIME NULL DEFAULT current_timestamp(),
	`ESTM_RLTT_ID` INT(11) UNSIGNED NOT NULL,
	`ESTM_RAKT_ID` INT(11) NOT NULL,
	`ESTM_ROWS` INT(11) NOT NULL DEFAULT 0,
	`ESTM_EXCEL_FILE_ID` INT(11) NULL COMMENT 'Reference to EXCEL_FAILI.ID',
	UNIQUE INDEX `PK_estimate` (`ESTM_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

-- Step 1: Alter the storage engine of `akti` to InnoDB
ALTER TABLE akti ENGINE = InnoDB;
ALTER TABLE lietotaji ENGINE = InnoDB;


-- Step 2: Add the foreign key constraint
ALTER TABLE estimate_files
ADD CONSTRAINT FK_estimate_akti
FOREIGN KEY (`ESTM_RAKT_ID`)
REFERENCES akti (`RAKT_ID`);

ALTER TABLE estimate_files
ADD CONSTRAINT FK_estimate_lietotaji
FOREIGN KEY (`ESTM_RLTT_ID`)
REFERENCES lietotaji (`RLTT_ID`);

CREATE TABLE estimate_files_detales (
	`ESFD_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `ESFD_ESTM_ID` INT(11) NOT NULL,
    `ESFD_TYPE` TINYINT(1) NOT NULL COMMENT '1=work, 2=material',
    `ESFD_CODE` CHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    `ESFD_TITLE` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
    `ESFD_WORK_TYPE_NAME` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
	`ESFD_STATUS` TINYINT(1) NOT NULL COMMENT '1=ok, 2=exist, 3=notexist, 4=amountnotset',
    `ESFD_SAVED` TINYINT(1) NOT NULL DEFAULT 0,
	UNIQUE INDEX `PK_estimate_detales` (`ESFD_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

ALTER TABLE estimate_files_detales
ADD CONSTRAINT FK_estimate_file
FOREIGN KEY (`ESFD_ESTM_ID`)
REFERENCES estimate_files (`ESTM_ID`)
ON DELETE CASCADE;

-- Add Excel file ID column to estimate_files table
ALTER TABLE estimate_files 
ADD COLUMN `ESTM_EXCEL_FILE_ID` INT(11) NULL COMMENT 'Reference to EXCEL_FAILI.ID';

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
VALUES ('STATUS_WORK_NOT_FOUND', 'Darbs nav atrasts katalogā Kalkulācija')
ON DUPLICATE KEY UPDATE `TEXT` = 'Darbs nav atrasts katalogā Kalkulācija';

-- Material not found in catalog  
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
VALUES ('STATUS_MATERIAL_NOT_FOUND', 'Materiāls nav atrasts DUIS katalogā Materiāli')
ON DUPLICATE KEY UPDATE `TEXT` = 'Materiāls nav atrasts katalogā Materiāli';

-- Work already exists in project
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
VALUES ('STATUS_WORK_EXISTS', 'Darbs jau pievienots projektam')
ON DUPLICATE KEY UPDATE `TEXT` = 'Darbs jau pievienots projektam';

-- Material already exists in project
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
VALUES ('STATUS_MATERIAL_EXISTS', 'Materiāls jau pievienots projektam')
ON DUPLICATE KEY UPDATE `TEXT` = 'Materiāls jau pievienots projektam';

-- Amount not set
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) 
VALUES ('STATUS_AMOUNT_NOT_SET', 'Darba vai materiāla apjoms nav norādīts')
ON DUPLICATE KEY UPDATE `TEXT` = 'Darba vai materiāla apjoms nav norādīts';


ALTER TABLE estimate_files_detales ADD COLUMN ESFD_TITLE VARCHAR(255) DEFAULT NULL;
ALTER TABLE estimate_files_detales ADD COLUMN ESFD_WORK_TYPE_NAME VARCHAR(255) DEFAULT NULL;