INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES 
('PLAN_CONSTRACTION_DATE', 'Plānotais izbūves sākums');

ALTER TABLE `auto_act_status`
	ADD COLUMN `AAST_CONSTRACTION_DATE` DATETIME NULL;

ALTER TABLE `auto_act_status_log`
	ADD COLUMN `AAST_CONSTRACTION_DATE` DATETIME NULL;

ALTER TABLE `akti`
	ADD COLUMN `RAKT_CONSTRACTION_DATE` DATETIME NULL DEFAULT NULL;