INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES 
('INFLATION', 'Inflācija'),
('INFLATION_PERCENT', 'Inflācijas procents');

ALTER TABLE `system_info`
	ADD COLUMN `INFLATION_PERCENT` FLOAT(3,2) NULL DEFAULT NULL;