ALTER TABLE `DARBI` ADD COLUMN  `DRBI_IMPORT_NO` INT NULL;
ALTER TABLE `TAME_DARBI` ADD COLUMN  `DRBI_IMPORT_NO` INT NULL;
ALTER TABLE `MATERIALI` ADD COLUMN  `MATR_IMPORT_NO` INT NULL;
ALTER TABLE `MATERIALI` ADD COLUMN  `MATR_IMPORT_NO` INT NULL;

ALTER TABLE `darbi`
	ADD CONSTRAINT `FK_DARBI_IMPORT_NO` FOREIGN KEY (`DRBI_IMPORT_NO`) REFERENCES `AKTI` (`RAKT_ID`);
ALTER TABLE `tame_darbi`
	ADD CONSTRAINT `FK_TAME_DARBI_IMPORT_NO` FOREIGN KEY (`DRBI_IMPORT_NO`) REFERENCES `AKTI` (`RAKT_ID`);
ALTER TABLE `materiali`
	ADD CONSTRAINT `FK_MATERIALI_IMPORT_NO` FOREIGN KEY (`MATR_IMPORT_NO`) REFERENCES `AKTI` (`RAKT_ID`);
ALTER TABLE `tame_materiali`
	ADD CONSTRAINT `FK_TAME_MATERIALI_IMPORT_NO` FOREIGN KEY (`MATR_IMPORT_NO`) REFERENCES `AKTI` (`RAKT_ID`);


INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES 
('IMPORT_NO_PROJECT', 'Imports no cita Projekta');
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES 
('ERROR_NOT_CHECKED', 'Neviens ieraksts nav atzīmēts.');