ALTER TABLE `AKTI` ADD COLUMN  `RAKT_ISSUE_DISTRICT` VARCHAR(30) COLLATE 'utf8_latvian_ci';
ALTER TABLE `AUTO_ACT_STATUS` ADD COLUMN  `ISSUE_DISTRICT` VARCHAR(30) COLLATE 'utf8_latvian_ci';
ALTER TABLE `AUTO_ACT_STATUS_LOG` ADD COLUMN  `ISSUE_DISTRICT` VARCHAR(30) COLLATE 'utf8_latvian_ci';

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`)
VALUES ('CONTRACT_DISTRICT', 'Līguma iecirknis');