ALTER TABLE `materiali` ADD `MATR_WORK_APROVE_DATE` DATE NULL DEFAULT NULL;
ALTER TABLE `tame_materiali` ADD `MATR_WORK_APROVE_DATE` DATE NULL DEFAULT NULL;

ALTER TABLE `materiali` ADD `MATR_APPROVE_DATE` DATETIME NULL;
ALTER TABLE `tame_materiali` ADD `MATR_APPROVE_DATE` DATETIME NULL;
