ALTER TABLE `lietotaji` ADD `RLTT_PROJECTOR` INT(1) NOT NULL DEFAULT 0;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES 
('PROJECTOR', 'Projektētajs');

ALTER TABLE `akti` ADD `RAKT_PROJECT` INT(1) NOT NULL DEFAULT 0;