ALTER TABLE `lietotaji` ADD `RLTT_PROJECTOR` INT(1) NOT NULL DEFAULT 0;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES 
('PROJECTOR', 'Projektētajs');

ALTER TABLE `akti` ADD `RAKT_PROJECT` INT(1) NOT NULL DEFAULT 0;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES 
('PROJECT', 'Projekts');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES 
('ADVANCED_PROJECT_SEARCH', 'Izvērsta projektu meklēšana');

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES 
('ST_WORK', 'ST darbi');

ALTER TABLE `darbi` ADD `DRBI_PIEZIMES` VARCHAR(250) NULL DEFAULT NULL COLLATE 'utf8_latvian_ci';
ALTER TABLE `tame_darbi` ADD `DRBI_PIEZIMES` VARCHAR(250) NULL DEFAULT NULL COLLATE 'utf8_latvian_ci';
ALTER TABLE `materiali` ADD `MATR_PIEZIMES` VARCHAR(250) NULL DEFAULT NULL COLLATE 'utf8_latvian_ci';
ALTER TABLE `tame_materiali` ADD `MATR_PIEZIMES` VARCHAR(250) NULL DEFAULT NULL COLLATE 'utf8_latvian_ci';
ALTER TABLE `darbi` CHANGE COLUMN `DRBI_KKAL_NORMATIVS` `DRBI_KKAL_NORMATIVS` FLOAT(8,2) NULL;

INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES 
('PROJECT_HEADER', 'SAGATAVE');

ALTER TABLE `kl_work_owners` ADD `KWOI_NOSAUKUMS2` VARCHAR(250) NULL DEFAULT NULL COLLATE 'utf8_latvian_ci';
INSERT INTO `FMK_MESSAGES` (`CODE`, `TEXT`) VALUES 
('NAME2', 'Nosaukums2');
INSERT INTO `kl_ref_kolonnas`(KLKL_COLUMN,KLKL_TITLE,KLKL_CATALOG,KLKL_IS_DEFAULT) VALUES 
('KWOI_NOSAUKUMS2', 'Nosaukums2', 'KL_DARBA_UZNEMEJI', 0);
UPDATE `kl_work_owners` SET `KWOI_NOSAUKUMS2` = `KWOI_NOSAUKUMS`; 

CREATE TABLE `excel_faili` (
	`EFLS_ID` INT(11) NOT NULL AUTO_INCREMENT,
	`EFLS_NOSAUKUMS` VARCHAR(250) NOT NULL COLLATE 'utf8_latvian_ci',
	`EFLS_DATUMS` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,	
	`EFLS_META_INFO` VARCHAR(250) NOT NULL DEFAULT 'application/vnd.ms-excel' COLLATE 'utf8_latvian_ci',
	`EFLS_RLTT_ID` INT(11) NOT NULL,
	`EFLS_RAKT_ID` INT(11) NOT NULL,
	PRIMARY KEY (`EFLS_ID`)
)
COLLATE='utf8_latvian_ci'
ENGINE=MyISAM
AUTO_INCREMENT=1
;