SELECT * FROM `darbi` WHERE 
`DRBI_RAKT_ID` IN (
SELECT `RAKT_ID` FROM `akti` WHERE `RAKT_STATUS` IN( 'CLOSE') AND `RAKT_IS_AUTO` = '1'
) AND  `DRBI_WORK_APROVE_DATE` IS NULL
AND DRBI_RAKT_ID = 27

SELECT MAX(`AAUD_DATUMS`)  FROM `akta_statusa_maina` WHERE `AAUD_STATUS` = 'CLOSE' AND `AAUD_RAKT_ID` = 27

UPDATE `darbi`
SET `DRBI_WORK_APROVE_DATE` = ( SELECT MAX(`AAUD_DATUMS`)  FROM `akta_statusa_maina` WHERE `AAUD_STATUS` = 'CLOSE' AND `AAUD_RAKT_ID` = DRBI_RAKT_ID )
WHERE 
`DRBI_RAKT_ID` IN (
SELECT `RAKT_ID` FROM `akti` WHERE `RAKT_STATUS` IN( 'CLOSE') AND `RAKT_IS_AUTO` = '1'
) AND  `DRBI_WORK_APROVE_DATE` IS NULL
AND DRBI_RAKT_ID = 27